src/objects/Object_Merge_Field__c.object
<CustomObject>
    <description>Represents a field to be merged.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, this field will be included in processing.</description>
        <inlineHelpText>If checked, this field will be included in processing.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Merge_Handler__c</fullName>
        <description>Handler for this field.</description>
        <inlineHelpText>Handler for this field.</inlineHelpText>
        <label>Object Merge Handler</label>
        <referenceTo>Object_Merge_Handler__c</referenceTo>
        <relationshipLabel>Object Merge Fields</relationshipLabel>
        <relationshipName>Object_Merge_Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Object Merge Field</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Merge Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object_Merge_Handler__c.object
<CustomObject>
    <description>Represents an object to be merged.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, this merge handler will be used during the Object merge process.</description>
        <inlineHelpText>If checked, this merge handler will be used during the Object merge process.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Object Merge Handler</label>
    <nameField>
        <label>Object API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Merge Handlers</pluralLabel>
    <recordTypes>
        <fullName>Parent_Handler</fullName>
        <active>true</active>
        <description>Handler for a parent object.</description>
        <label>Parent Handler</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectMergeValidatorTest.cls
@isTest
public class ObjectMergeValidatorTest {

    @isTest
    private static void testInsertInvalidField() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );
        insert omh;

        Object_Merge_Field__c omf = new Object_Merge_Field__c (
            Active__c               = true,
            Object_Merge_Handler__c = omh.Id,
            Name                    = 'Not a valid field name'
        );

        Test.startTest();
            try{
                insert omf;
                system.assert( false, 'Object Merge field with illegal name was inserted without proper validation');
            } catch (Exception e) {

            }
        Test.stopTest();

    }

    @isTest
    private static void testUpdateInvalidField() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );
        insert omh;

        Object_Merge_Field__c omf = new Object_Merge_Field__c (
            Active__c               = true,
            Object_Merge_Handler__c = omh.Id,
            Name                    = 'Name'
        );
        insert omf;
        omf.Name = 'Not a valid field name';

        Test.startTest();
            try{
                update omf;
                system.assert( false, 'Object Merge field with illegal name was updated without proper validation');
            } catch (Exception e) {

            }
        Test.stopTest();

    }

    @isTest
    private static void testInsertInvalidHandler() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Not a valid object name',
            RecordTypeId    = parentHandlerId
        );

        Test.startTest();
            try{
                insert omh;
                system.assert( false, 'Object Merge field with illegal name was updated without proper validation');
            } catch (Exception e) {

            }
        Test.stopTest();
       

    }

    @isTest
    private static void testUpdateInvalidHandler() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );
        insert omh;
        omh.Name = 'Not a valid object name';

        Test.startTest();
            try{
                update omh;
                system.assert( false, 'Object Merge field with illegal name was updated without proper validation');
            } catch (Exception e) {

            }
        Test.stopTest();

    }

    @isTest
    private static void testInsertValidField() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );
        insert omh;

        Object_Merge_Field__c omf = new Object_Merge_Field__c (
            Active__c               = true,
            Object_Merge_Handler__c = omh.Id,
            Name                    = 'Name'
        );

        Test.startTest();
            insert omf;
        Test.stopTest();

    }

    @isTest
    private static void testUpdateValidField() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );
        insert omh;

        Object_Merge_Field__c omf = new Object_Merge_Field__c (
            Active__c               = true,
            Object_Merge_Handler__c = omh.Id,
            Name                    = 'Name'
        );
        insert omf;
        omf.Name = 'Id';

        Test.startTest();
            update omf;
        Test.stopTest();

    }

    @isTest
    private static void testInsertValidHandler() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );

        Test.startTest();
            insert omh;
        Test.stopTest();
       

    }

    @isTest
    private static void testUpdateValidHandler() {

        Id parentHandlerId = Object_Merge_Handler__c.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Parent_Handler').getRecordTypeId();
        //Start by creating the object merge handler
        Object_Merge_Handler__c omh = new Object_Merge_Handler__c (
            Active__c       = true,
            Name            = 'Account',
            RecordTypeId    = parentHandlerId
        );
        insert omh;
        omh.Name = 'Contact';

        Test.startTest();
            update omh;
        Test.stopTest();

    }

}